// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetServerPort() {
  return window['go']['main']['App']['GetServerPort']();
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function OpenInBrowser() {
  return window['go']['main']['App']['OpenInBrowser']();
}

export function StartServer() {
  return window['go']['main']['App']['StartServer']();
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}
