// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetServerPort():Promise<number>;

export function GetServerStatus():Promise<string>;

export function OpenInBrowser():Promise<void>;

export function StartServer():Promise<void>;

export function StopServer():Promise<void>;
